#:schema node_modules/wrangler/config-schema.json
name = "dingyuezhuanhuan-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e5bca0c585e741bcaf5a01588cc21913" }
]

[assets]
directory = "./public"
